/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package multilevel.view;

import javax.swing.*;
import multilevel.model.MultilevelSparseMultigraph;

/**
 *
 * @author Spiros
 */
public class MainUI extends javax.swing.JFrame {

    
    private MultilevelSparseMultigraph mg;
    /**
     * Creates new form TestUI
     */
    public MainUI() {
        this.mg = new MultilevelSparseMultigraph();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog2 = new javax.swing.JDialog();
        pageRankOptions2 = new multilevel.view.PageRankOptions();
        errorDialog = new javax.swing.JDialog();
        jButton10 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDialog1 = new javax.swing.JDialog();
        layoutSelectionDialog = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        selectLayoutComboBox = new javax.swing.JComboBox();
        selectLayoutOKButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        graphFoundationPanel1 = new multilevel.view.GraphFoundationPanel();
        logTxtArea1 = new multilevel.view.LogTextArea();
        jPanel3 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        tabbedPane11 = new multilevel.view.SideTabbedPane();
        logGraphSplitPane1 = new multilevel.view.LogGraphSplitPane();
        jToolBar1 = new javax.swing.JToolBar();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        newButton = new javax.swing.JButton();
        interfaceOpenButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton7 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jComboBox1 = new javax.swing.JComboBox();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        mainMenuBar3 = new multilevel.view.MainMenuBar();

        jDialog2.setTitle("Page Rank Options");
        jDialog2.setAlwaysOnTop(true);
        jDialog2.setMinimumSize(new java.awt.Dimension(210, 200));
        jDialog2.setResizable(false);

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addComponent(pageRankOptions2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addComponent(pageRankOptions2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 33, Short.MAX_VALUE))
        );

        errorDialog.setTitle("Error");
        errorDialog.setAlwaysOnTop(true);
        errorDialog.setIconImage(null);
        errorDialog.setMinimumSize(new java.awt.Dimension(200, 120));
        errorDialog.setResizable(false);

        jButton10.setText("OK");
        jButton10.setAlignmentY(0.0F);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setMaximumSize(new java.awt.Dimension(48, 23));
        jButton10.setMinimumSize(new java.awt.Dimension(48, 23));
        jButton10.setPreferredSize(new java.awt.Dimension(48, 23));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dialog-error.png"))); // NOI18N
        jLabel1.setText("Error!");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("View Log Area for more info.");

        javax.swing.GroupLayout errorDialogLayout = new javax.swing.GroupLayout(errorDialog.getContentPane());
        errorDialog.getContentPane().setLayout(errorDialogLayout);
        errorDialogLayout.setHorizontalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        errorDialogLayout.setVerticalGroup(
            errorDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(errorDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jDialog1.setTitle("PCI Options");
        jDialog1.setAlwaysOnTop(true);
        jDialog1.setMinimumSize(new java.awt.Dimension(300, 185));
        jDialog1.setModal(true);
        jDialog1.setResizable(false);
        jDialog1.getContentPane().setLayout(new java.awt.FlowLayout());
        pciOpt = new PCIOptions();
        jDialog1.add(pciOpt);

        layoutSelectionDialog.setTitle("Select Layout");
        layoutSelectionDialog.setAlwaysOnTop(true);
        layoutSelectionDialog.setMinimumSize(new java.awt.Dimension(200, 140));
        layoutSelectionDialog.setModal(true);
        layoutSelectionDialog.setPreferredSize(new java.awt.Dimension(200, 140));
        layoutSelectionDialog.setResizable(false);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit-select-all.png"))); // NOI18N
        jLabel3.setText("Select Graph Layout");

        selectLayoutComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Circle", "Fruchterman - Reingold", "Fruchterman - Reingold 2", "ISOM", "Kamada - Kawai", "Spring" }));

        selectLayoutOKButton.setText("OK");
        selectLayoutOKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectLayoutOKButtonActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        javax.swing.GroupLayout layoutSelectionDialogLayout = new javax.swing.GroupLayout(layoutSelectionDialog.getContentPane());
        layoutSelectionDialog.getContentPane().setLayout(layoutSelectionDialogLayout);
        layoutSelectionDialogLayout.setHorizontalGroup(
            layoutSelectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layoutSelectionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layoutSelectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layoutSelectionDialogLayout.createSequentialGroup()
                        .addGap(0, 18, Short.MAX_VALUE)
                        .addComponent(selectLayoutOKButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(16, 16, 16))
                    .addComponent(selectLayoutComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layoutSelectionDialogLayout.setVerticalGroup(
            layoutSelectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layoutSelectionDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectLayoutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layoutSelectionDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectLayoutOKButton)
                    .addComponent(jButton2))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MultiLayer Complex Networks Analysis");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setForeground(new java.awt.Color(240, 240, 240));
        jPanel3.setPreferredSize(new java.awt.Dimension(1024, 768));

        jSplitPane1.setDividerLocation(960);
        jSplitPane1.setResizeWeight(0.5);

        tabbedPane11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jSplitPane1.setRightComponent(tabbedPane11);

        logGraphSplitPane1.setUI(this);
        jSplitPane1.setLeftComponent(logGraphSplitPane1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        jDialog2.setLocationRelativeTo(this);
        jDialog1.setLocationRelativeTo(this);
        layoutSelectionDialog.setLocationRelativeTo(this);
        errorDialog.setLocationRelativeTo(this);

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jSeparator3.setBackground(new java.awt.Color(255, 255, 0));
        jSeparator3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(191, 209, 227), 10));
        jSeparator3.setMaximumSize(new java.awt.Dimension(6, 29));
        jSeparator3.setMinimumSize(new java.awt.Dimension(6, 29));
        jSeparator3.setPreferredSize(new java.awt.Dimension(6, 29));
        jSeparator3.setSeparatorSize(new java.awt.Dimension(6, 29));
        jToolBar1.add(jSeparator3);

        newButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/document-new.png"))); // NOI18N
        newButton.setText("New");
        newButton.setToolTipText("");
        newButton.setFocusable(false);
        newButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        newButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(newButton);

        interfaceOpenButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/document-open.png"))); // NOI18N
        interfaceOpenButton.setText("Open");
        interfaceOpenButton.setFocusable(false);
        interfaceOpenButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        interfaceOpenButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(interfaceOpenButton);
        jToolBar1.add(jSeparator1);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconarchive/Hands-One-Finger-icon.png"))); // NOI18N
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new multilevel.control.MouseToggle(this));
        jToolBar1.add(jButton7);
        jToolBar1.add(jSeparator2);

        jComboBox1.setAutoscrolls(true);
        jComboBox1.setEnabled(false);
        jComboBox1.setMaximumSize(new java.awt.Dimension(150, 20));
        jComboBox1.addActionListener(new multilevel.control.SingleViewToggleListener(this));
        jToolBar1.add(jComboBox1);
        jToolBar1.add(jSeparator5);

        jButton5.setText("Single View");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new multilevel.control.SingleViewToggleListener(this));
        jToolBar1.add(jButton5);

        jButton6.setText("Multi View");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new multilevel.control.SingleViewToggleListener(this));
        jToolBar1.add(jButton6);
        jToolBar1.add(jSeparator4);

        setJMenuBar(mainMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE))
        );

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.setEnabled(true);
        errorDialog.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void selectLayoutOKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectLayoutOKButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectLayoutOKButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog errorDialog;
    private javax.swing.JButton interfaceOpenButton;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JDialog jDialog1;
    private PCIOptions pciOpt;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private multilevel.view.GraphFoundationPanel graphFoundationPanel1;
    private multilevel.view.LogTextArea logTxtArea1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDialog layoutSelectionDialog;
    private multilevel.view.LogGraphSplitPane logGraphSplitPane1;
    private multilevel.view.MainMenuBar mainMenuBar3;
    private javax.swing.JButton newButton;
    private multilevel.view.PageRankOptions pageRankOptions2;
    private javax.swing.JComboBox selectLayoutComboBox;
    private javax.swing.JButton selectLayoutOKButton;
    private multilevel.view.SideTabbedPane tabbedPane11;
    // End of variables declaration//GEN-END:variables
    
    
    
    /**
     * @return the jSplitPane1
     */
    public javax.swing.JSplitPane getjSplitPane1() {
        return jSplitPane1;
        
    }

    /**
     * @param jSplitPane1 the jSplitPane1 to set
     */
    public void setjSplitPane1(javax.swing.JSplitPane jSplitPane1) {
        this.jSplitPane1 = jSplitPane1;
    }

    /**
     * @return the graph
     */
    /*public GraphZoomScrollPane getGraphFoundationPanel1() {
        return getLogGraphSplitPane1().getGraphPanel().getGraph();
    }*/
    
    /**
     *
     * @param i
     * @return JMenu item
     */
    public JMenuItem getMenuItem(int i){
        switch (i) {
            case 1:
                return mainMenuBar3.getMenu2();
            case 2:
                return mainMenuBar3.getOpenMenuItem();
            case 3:
                return mainMenuBar3.getMenu3();
            case 4:
                return mainMenuBar3.getMultiplexBetweenness();
            case 5:
                return mainMenuBar3.getMultiplexPageRank();
            case 6:
                return mainMenuBar3.getMultiplexUndirDegree();
            case 7:
                return mainMenuBar3.getMultiplexInDegree();
            case 8:
                return mainMenuBar3.getMultiplexOutDegree();   
            case 9:
                return mainMenuBar3.getOptionsMenuItem();
            case 10:
                return mainMenuBar3.getExportGraphsMenuItem();
            case 11:
                return mainMenuBar3.getMultilayerUndirDegree();
            case 12:
                return mainMenuBar3.getMultilayerInDegree();
            case 13:
                return mainMenuBar3.getMultilayerOutDegree();
            case 14:
                return mainMenuBar3.getMultilayerPCI();
            
            default:
                return null;
        }
    }

    /**
     * @return the jComboBox1
     */
    public javax.swing.JComboBox getjComboBox1() {
        return jComboBox1;
    }

    /**
     * @param jComboBox1 the jComboBox1 to set
     */
    public void setjComboBox1(javax.swing.JComboBox jComboBox1) {
        this.jComboBox1 = jComboBox1;
    }

    /**
     * @return the logGraphSplitPane1
     */
    public multilevel.view.LogGraphSplitPane getLogGraphSplitPane1() {
        return logGraphSplitPane1;
    }

    /**
     * @param logGraphSplitPane1 the logGraphSplitPane1 to set
     */
    public void setLogGraphSplitPane1(multilevel.view.LogGraphSplitPane logGraphSplitPane1) {
        this.logGraphSplitPane1 = logGraphSplitPane1;
    }

    /**
     * @return the logTxtArea1
     */
    public multilevel.view.LogTextArea getLogTxtArea1() {
        return logTxtArea1;
    }

    /**
     * @return the graphFoundationPanel1
     */
    public multilevel.view.GraphFoundationPanel getGraphFoundationPanel1() {
        return graphFoundationPanel1;
    }

    /**
     * @return the tabbedPane11
     */
    public multilevel.view.SideTabbedPane getTabbedPane11() {
        return tabbedPane11;
    }

    /**
     * @param tabbedPane11 the tabbedPane11 to set
     */
    public void setTabbedPane11(multilevel.view.SideTabbedPane tabbedPane11) {
        this.tabbedPane11 = tabbedPane11;
    }

    /**
     * @return the jButton7
     */
    public javax.swing.JButton getjButton7() {
        return jButton7;
    }

    /**
     * @return the mg
     */
    public MultilevelSparseMultigraph getMg() {
        System.out.println("MG get.");
        return mg;
    }

    /**
     * @param mg the mg to set
     */
    public void setMg(MultilevelSparseMultigraph mg) {
        this.mg = mg;
    }

    /**
     * @return the jDialog2
     */
    public javax.swing.JDialog getjDialog2() {
        return jDialog2;
    }

    /**
     * @return the pageRankOptions2
     */
    public multilevel.view.PageRankOptions getPageRankOptions2() {
        return pageRankOptions2;
    }

    /**
     * @return the jDialog1
     */
    public javax.swing.JDialog getErrorDialog() {
        return errorDialog;
    }

    /**
     * @return the pciOpt
     */
    public PCIOptions getPciOpt() {
        return pciOpt;
    }

    /**
     * @return the jDialog1
     */
    public javax.swing.JDialog getjDialog1() {
        return jDialog1;
    }

    /**
     * @return the interfaceOpenButton
     */
    public javax.swing.JButton getInterfaceOpenButton() {
        return interfaceOpenButton;
    }

    /**
     * @return the newButton
     */
    public javax.swing.JButton getNewButton() {
        return newButton;
    }

    /**
     * @return the layoutSelectionDialog
     */
    public javax.swing.JDialog getLayoutSelectionDialog() {
        return layoutSelectionDialog;
    }

    /**
     * @return the selectLayoutOKButton
     */
    public javax.swing.JButton getSelectLayoutOKButton() {
        return selectLayoutOKButton;
    }

    /**
     * @return the selectLayoutComboBox
     */
    public javax.swing.JComboBox getSelectLayoutComboBox() {
        return selectLayoutComboBox;
    }
}


