/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multilevel.view;

/**
 *
 * @author Spiros
 */
public class PCIOptions extends javax.swing.JPanel {

    /**
     * Creates new form PCIOptions
     */
    public PCIOptions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pciMethodComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        numberOfLayersComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pciCancelButton = new javax.swing.JButton();
        pciOkButton = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(205, 150));
        setMinimumSize(new java.awt.Dimension(205, 150));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(205, 150));

        jLabel1.setText("Select PCI calculation method :");

        pciMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Original (μ-PCI)", "Layer-agnostic (laPCI)", "All-layers (alPCI)", "Layer-symmetric (lsPCI)", "Minimal-layers (mlPCI)", "sca-mlPCI" }));

        jLabel2.setText("Number of Layers :");

        numberOfLayersComboBox.setEnabled(false);
        numberOfLayersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfLayersComboBoxActionPerformed(evt);
            }
        });

        pciCancelButton.setText("Cancel");

        pciOkButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pciOkButton.setLabel("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(pciOkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(50, 50, 50)
                                .addComponent(pciCancelButton)
                                .addGap(10, 10, 10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(numberOfLayersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(66, 66, 66)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pciMethodComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pciMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(numberOfLayersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pciCancelButton)
                            .addComponent(pciOkButton))
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void numberOfLayersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfLayersComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberOfLayersComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox numberOfLayersComboBox;
    private javax.swing.JButton pciCancelButton;
    private javax.swing.JComboBox pciMethodComboBox;
    private javax.swing.JButton pciOkButton;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the numberOfLayersComboBox
     */
    public javax.swing.JComboBox getNumberOfLayersComboBox() {
        return numberOfLayersComboBox;
    }

    /**
     * @return the pciCancelButton
     */
    public javax.swing.JButton getPciCancelButton() {
        return pciCancelButton;
    }

    /**
     * @return the pciMethodComboBox
     */
    public javax.swing.JComboBox getPciMethodComboBox() {
        return pciMethodComboBox;
    }

    /**
     * @return the pciOkButton
     */
    public javax.swing.JButton getPciOkButton() {
        return pciOkButton;
    }
}
